### ISSUE TITLE
make permissions permanent

### ISSUE THREAD

**Issue by toppk** [MartinEmrich/kb#2]
here is an example of how to make permissions permanent, on modern systemd boxes

# cat /etc/udev/rules.d/90-ceph-marker.rules
ENV{DM_VG_NAME}=="marker-*" ENV{DM_LV_NAME}=="*+raw" OWNER="ceph"
# udevadm  control -R

**Comment by MartinEmrich** [comment]
I added an example from my actual production machine.. Different approach, but same effect.

Thanks for the issue, I forgot to add it to my doc...
